version: '3.8'

services:
  hero:
    image: hemanth9030/demo:0.0.1
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql-db:3308/hero?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.username: root
      spring.datasource.password: root
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3308
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3308/hero
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

